server:
    port: 8081
    contextPath: /userclient
security:
    basic:
        enabled: false
config:
    oauth2:
        clientID: user_admin_client
        clientSecret: secret
        clientScopes:
              - user_admin_client
              - internal_client
    user:
        personalinfo: http://localhost:9091/user/user
        userlist: http://localhost:9091/user/user/list
        rolelist: http://localhost:9091/user/role/list
        delete: http://localhost:9091/user/user/delete
        info: http://localhost:9091/user/user/info
        update: http://localhost:9091/user/user/update
        updatepersonal: http://localhost:9091/user/user/personal/update
        roleoptions: http://localhost:9091/user/role/options
        clientoptions: http://localhost:9091/user/client/list/options
        moduleroleoptions: http://localhost:9091/user/modulerole/list/options
        save: http://localhost:9091/user/user/save
        clientlist: http://localhost:9091/user/client/list
        clientinfo: http://localhost:9091/user/client/info
        clientupdate: http://localhost:9091/user/client/update
        clientsave: http://localhost:9091/user/client/save
        clientdelete: http://localhost:9091/user/client/delete
        #moduleRole
        modulerolelist: http://localhost:9091/user/modulerole/list
        moduleroleinfo: http://localhost:9091/user/modulerole/info
        moduleroleupdate: http://localhost:9091/user/modulerole/update
        modulerolesave: http://localhost:9091/user/modulerole/save
        moduleroledelete: http://localhost:9091/user/modulerole/delete
        clientoptionsofmodulerole: http://localhost:9091/user/client/list/module/options
        #module
        modulelist: http://localhost:9091/user/module/list
        moduleinfo: http://localhost:9091/user/module/info
        moduleupdate: http://localhost:9091/user/module/update
        modulesave: http://localhost:9091/user/module/save
        moduledelete: http://localhost:9091/user/module/delete
        moduleparentoptions: http://localhost:9091/user/module/list/parent/options
        moduleparentoptionsofclient: http://localhost:9091/user/module/list/parent/client/options
        moduleroleoptionsofmodule: http://localhost:9091/user/modulerole/list/module/options