server:
    port: 8082
    contextPath: /cmsclient
security:
    basic:
        enabled: false
config:
    oauth2:
        clientID: cms_admin_client
        clientSecret: secret
        clientScopes:
              - cms_admin_client
              - internal_client
    cms:
        #website
        websitelist: http://localhost:9092/cms/website/list
        websiteinfo: http://localhost:9092/cms/website/info
        websiteupdate: http://localhost:9092/cms/website/update
        websitesave: http://localhost:9092/cms/website/save
        websitedelete: http://localhost:9092/cms/website/delete
        websiteoptions: http://localhost:9092/cms/website/options
        #resource
        resourceTypes:
                - css
                - js
        resourcelist: http://localhost:9092/cms/resource/list
        resourceinfo: http://localhost:9092/cms/resource/info
        resourceupdate: http://localhost:9092/cms/resource/update
        resourcesave: http://localhost:9092/cms/resource/save
        resourcedelete: http://localhost:9092/cms/resource/delete
        resourceoptions: http://localhost:9092/cms/resource/options
        #template
        templateLayoutTypes:
                - static
                - fluid
        templateLayoutScales:
                - 3*3
                - 3*4
                - 4*3
                - 4*4
        templatelist: http://localhost:9092/cms/template/list
        templateinfo: http://localhost:9092/cms/template/info
        templateupdate: http://localhost:9092/cms/template/update
        templatesave: http://localhost:9092/cms/template/save
        templatedelete: http://localhost:9092/cms/template/delete
        templateoptionsofwebsite: http://localhost:9092/cms/template/options/bywebsite
        #block
        blockTypes:
                - 静态内容
                - 热点新闻
                - 最新新闻
                - 投票
                - 导航
                - 文件库
                - 自定义内容
        blocklist: http://localhost:9092/cms/block/list
        blockinfo: http://localhost:9092/cms/block/info
        blockupdate: http://localhost:9092/cms/block/update
        blocksave: http://localhost:9092/cms/block/save
        blockdelete: http://localhost:9092/cms/block/delete
        blockoptions: http://localhost:9092/cms/block/options
        #news
        newslist: http://localhost:9092/cms/news/list
        newsinfo: http://localhost:9092/cms/news/info
        newsupdate: http://localhost:9092/cms/news/update
        newssave: http://localhost:9092/cms/news/save
        newsdelete: http://localhost:9092/cms/news/delete
        #newsType
        newstypelist: http://localhost:9092/cms/newstype/list
        newstypeinfo: http://localhost:9092/cms/newstype/info
        newstypeupdate: http://localhost:9092/cms/newstype/update
        newstypesave: http://localhost:9092/cms/newstype/save
        newstypedelete: http://localhost:9092/cms/newstype/delete
        newstypeoptionsofwebsite: http://localhost:9092/cms/newstype/options/bywebsite
        #poll
        polllist: http://localhost:9092/cms/poll/list
        pollinfo: http://localhost:9092/cms/poll/info
        pollupdate: http://localhost:9092/cms/poll/update
        pollsave: http://localhost:9092/cms/poll/save
        polldelete: http://localhost:9092/cms/poll/delete
        polloptions: http://localhost:9092/cms/poll/options
        #pollOption
        polloptionlist: http://localhost:9092/cms/polloption/list
        polloptioninfo: http://localhost:9092/cms/polloption/info
        polloptionupdate: http://localhost:9092/cms/polloption/update
        polloptionsave: http://localhost:9092/cms/polloption/save
        polloptiondelete: http://localhost:9092/cms/polloption/delete
        #operation
        relatedOperations:
                - 投票
                - 新增文章
        optionlist: http://localhost:9092/cms/operation/list
        optioninfo: http://localhost:9092/cms/operation/info
        optionupdate: http://localhost:9092/cms/operation/update
        optionsave: http://localhost:9092/cms/operation/save
        optiondelete: http://localhost:9092/cms/operation/delete
        #navigate
        navigateTypes:
                        - 文章
                        - 新闻
                        - 多媒体
                        - 无内容
        navigatelist: http://localhost:9092/cms/navigate/list
        navigateinfo: http://localhost:9092/cms/navigate/info
        navigateupdate: http://localhost:9092/cms/navigate/update
        navigatesave: http://localhost:9092/cms/navigate/save
        navigatedelete: http://localhost:9092/cms/navigate/delete
        navigateparentoptions: http://localhost:9092/cms/navigate/parent/options
        #fileLibrary
        filelibrarylist: http://localhost:9092/cms/filelibrary/list
        filelibraryinfo: http://localhost:9092/cms/filelibrary/info
        filelibraryupdate: http://localhost:9092/cms/filelibrary/update
        filelibrarysave: http://localhost:9092/cms/filelibrary/save
        filelibrarydelete: http://localhost:9092/cms/filelibrary/delete
        filelibrarylistbytype: http://localhost:9092/cms/filelibrary/list/bytype

        #fileLibraryType
        filelibrarytypelist: http://localhost:9092/cms/filelibrarytype/list
        filelibrarytypeinfo: http://localhost:9092/cms/filelibrarytype/info
        filelibrarytypeupdate: http://localhost:9092/cms/filelibrarytype/update
        filelibrarytypesave: http://localhost:9092/cms/filelibrarytype/save
        filelibrarytypedelete: http://localhost:9092/cms/filelibrarytype/delete
        filelibrarytypeoptionsofwebsite: http://localhost:9092/cms/filelibrarytype/options/bywebsite
        #article
        articlelist: http://localhost:9092/cms/article/list
        articleinfo: http://localhost:9092/cms/article/info
        articleupdate: http://localhost:9092/cms/article/update
        articlesave: http://localhost:9092/cms/article/save
        articledelete: http://localhost:9092/cms/article/delete
        articleoptions: http://localhost:9092/cms/article/options
